version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    env_file: .env
    environment:
      - POSTGRES_USER=theo
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=attendeasy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U theo -P test"]
      interval: 5s
      timeout: 5s
      retries: 30
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
